name: Build ImmortalWrt for PVE

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cleanup and install deps
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses5-dev gawk git \
          libssl-dev gettext zlib1g-dev unzip python3

      - name: Clone ImmortalWrt source
        run: |
          git clone https://github.com/immortalwrt/immortalwrt.git
          cd immortalwrt

      - name: Add external feeds (iStore & OpenClash & Themes)
        run: |
          cd immortalwrt
          echo "src-git istore https://github.com/linkease/istore;main" >> feeds.conf.default
          echo "src-git openclash https://github.com/vernesong/OpenClash.git" >> feeds.conf.default
          echo "src-git argon https://github.com/jerrykuku/luci-theme-argon.git" >> feeds.conf.default
          cat feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Copy config file
        run: |
          cp .config immortalwrt/.config
          cd immortalwrt

      - name: Fix rootfs partition size
        run: |
          cd immortalwrt
          echo "CONFIG_TARGET_ROOTFS_PARTSIZE=2048" >> .config
          echo "CONFIG_TARGET_ROOTFS_EXT4FS=y" >> .config
          make defconfig

      - name: Build firmware
        run: |
          cd immortalwrt
          make download -j$(nproc)
          make -j$(nproc)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-firmware
          path: immortalwrt/bin/targets/x86/64/
